apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - name: pinger
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            echo "$(date): Pinging /serviceup endpoint"
            curl -s http://flask-service/serviceup || echo "Failed to reach /serviceup"
            sleep 10
          done
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
