apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: flask-app
type: Opaque
data:
  postgres-password: cGFzc3dvcmQxMjM= # base64 encoded "password123"
  postgres-user: cG9zdGdyZXM= # base64 encoded "postgres"
  postgres-db: Zmxhc2tkYg== # base64 encoded "flaskdb"
