apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: flask-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-immediate
  resources:
    requests:
      storage: 20Gi
